version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
